version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: node-k8s-app
    CLUSTER_NAME: enterprise-eks
    AWS_ACCOUNT_ID: 150460248370

phases:

  # =========================
  # INSTALL PHASE
  # =========================
  install:
    runtime-versions:
      docker: 20

    commands:
      - echo "=== CHECKING TOOLS ==="
      - aws --version
      - docker --version
      - kubectl version --client

  # =========================
  # PRE BUILD (ECR LOGIN)
  # =========================
  pre_build:
    commands:
      - echo "=== LOGIN TO AMAZON ECR ==="

      - aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS \
        --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  # =========================
  # BUILD IMAGE
  # =========================
  build:
    commands:
      - echo "=== BUILDING DOCKER IMAGE ==="

      - docker build -t $ECR_REPOSITORY:latest .

      - echo "=== TAGGING IMAGE ==="

      - docker tag $ECR_REPOSITORY:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - echo "=== PUSHING IMAGE TO ECR ==="

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

  # =========================
  # DEPLOY TO EKS
  # =========================
  post_build:
    commands:
      - echo "=== UPDATE KUBECONFIG ==="

      - aws eks update-kubeconfig \
        --name $CLUSTER_NAME \
        --region $AWS_REGION

      - echo "=== DEPLOYING TO EKS ==="

      - kubectl apply -f k8/

      - echo "=== DEPLOYMENT COMPLETE ==="

artifacts:
  files:
    - "**/*"
